---
# role: user
# tasks: user.yml
# description: Creates and configures one user

- name: Create user "{{ user.name }}"
  user:
    name: "{{ user.name }}"
    shell: "{{ user.shell }}"
    uid: "{{ user.uid }}"
    groups:
      - sudo
      - users
      - docker

- name: Add user "{{ user.name }}" to sudoers
  lineinfile:
    path: "/etc/sudoers.d/{{ user.name }}"
    line: "{{ user.name }} ALL=(ALL) NOPASSWD: ALL"
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'
  become_user: root
  become: true

- name: Create user persistent data directory
  file:
    path: "{{ server.persistent_data_path }}/{{ user.name }}"
    state: directory
    mode:  '2775'
    owner: "{{ user.uid }}"
    group: users

- name: Set authorized keys taken from github
  authorized_key:
    user: "{{ user.name }}"
    state: present
    key: "https://github.com/{{ user.github }}.keys"
  become_user: root
  become: true

- name: Generate kube SSH key
  openssh_keypair:
    path: "~/.ssh/id_rsa_kube"
    type: rsa
    size: 4096
    state: present
    force: no
  become_user: "{{ user.name }}"
  become: true

- name: Set authorized keys for kube user
  authorized_key:
    user: "kube"
    state: present
    key: "{{ ssh_key_file }}"
  with_file:
    - "/home/{{ user.name }}/.ssh/id_rsa_kube.pub"
  loop_control:
    loop_var: ssh_key_file

- name: Create scripts directory
  file:
    path: "/home/{{ user.name }}/midgard/"
    state: directory
    owner: "{{ user.uid }}"
    group: "{{ user.uid }}"
    mode: '0755'

- name: Create scripts symlink
  file:
    src: "/home/kube/{{ repo.name }}/scripts"
    dest: "/home/{{ user.name }}/midgard/{{ repo.name }}"
    state: link
  with_items: "{{ accounts.kube.repositories }}"
  when: repo.scripts == true
  loop_control:
    loop_var: repo
