---
# role: user
# tasks: user.yml
# description: Creates and configures one user

- name: Create user "{{ user.name }}"
  user:
    name: "{{ user.name }}"
    shell: "{{ user.shell }}"
    uid: "{{ user.uid }}"
    groups:
      - sudo
      - users
      - docker

- name: Add user "{{ user.name }}" to sudoers
  lineinfile:
    path: "/etc/sudoers.d/{{ user.name }}"
    line: "{{ user.name }} ALL=(ALL) NOPASSWD: ALL"
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'

- name: Create user persistent data directory
  file:
    path: "{{ server.persistent_data_path }}/{{ user.name }}"
    state: directory
    mode:  '2775'
    owner: "{{ user.uid }}"
    group: users

- name: Set authorized keys taken from github
  authorized_key:
    user: "{{ user.name }}"
    state: present
    key: "https://github.com/{{ user.github }}.keys"

- name: Generate kube SSH key
  openssh_keypair:
    path: "~/.ssh/id_rsa_kube"
    type: rsa
    size: 4096
    state: present
    force: no
  become_user: "{{ user.name }}"
  become: true


- name: Set authorized keys for kube user
  authorized_key:
    user: "kube"
    state: present
    key: "{{ item }}"
  with_file:
    - "/home/{{ user.name }}/.ssh/id_rsa_kube.pub"
